### ISSUE TITLE
Lab 2- step 2.1 

### ISSUE THREAD

**Issue by fitz0017** [CNA-Tech/PKS-Ninja#12]
step 2.1 - this has happened to two users.  The openssl s_client command doesn't resolve when using the hostname.  Works when using IP address for NSX Manager.  DNS record looks correct in DNS manager, but something seems to be preventing it.  Error below.

![image](https://user-images.githubusercontent.com/11213335/49155375-c79ba180-f2e8-11e8-83de-352787b3a8c9.png)

**Comment by natereid72** [comment]
This has been resolved as an issue with the cli-vm name resolution switch config issue. Needs to be fixed in base template but work around is to modify the /etc/nsswitch.conf per the following:

Need to modify file in cli-vm template:

Edit /etc/nsswitch.conf
Change: "hosts: files mdns4_minimal [NOTFOUND=return] dns"
To: "hosts: files dns"

**Comment by afewellvmware** [comment]
resolved with Nate's patch, closing
