### ISSUE TITLE
Update recommendations against using Helm with Tiller with cluster-admin privileges

### ISSUE THREAD

**Issue by scottslowe** [CNA-Tech/PKS-Ninja#290]
Any recommendations to use Helm should recommend "Tillerless" Helm (Helm without Tiller), or should advise users to properly secure Tiller against potential security concerns.

Helm/Tiller security concerns are outlined here:

Exploring the Security of Helm - https://engineering.bitnami.com/articles/helm-security.html

Securing your Helm Installation - https://github.com/helm/helm/blob/master/docs/securing_installation.md

**Comment by afewellvmware** [comment]
Thanks so much Scott, I will get this in queue for update at high priority, i have a bunch of updates to do for wwko next week and will try to squeeze this in, if not shortly after unless someone else gets to it first. 

Thanks so much!!

**Comment by afewellvmware** [comment]
Hi @scottslowe thanks again for these links, I have gone through everything and learned a lot! I will add a link to these resources from the guides. From reviewing these links, I dont see anything in our lab guide that I think should be changed other than providing the links, happy to discuss further on that. 

Net net is that our helm guide as we have it now does use kubernetes rbac and create a dedicated service account for tiller. It does also use the cluster-admin priviledge to back the tiller service account, and this is exactly the same approach that we take across most of our training not just within PKS ninja but across VMware and most training programs not just within k8s but across the board. It is also the method used in this Heptio blog: https://heptio.com/resources/tutorials/aws-qs-helm-wordpress/ as the tiller account needs to be bound to some permissions so as typical in educational labs using admin makes sense here to avoid needing to have beginner students do granular apigroup/resource/verb rule to rolebinding configuration for the level of materials where that level of depth is not appropriate. 

I also do not think it would be more appropriate to use tillerless in this case as it does not solve for many common needs and tiller is still commonly recommended, assuming rbac and certificates are implemented in appropriate capacity for production grade environments. Across the board throughout our training in our student lab environments we regularly bypass production-grade best practices specifically around use of admin accounts and as lack of publicly registered domains and certificate authorities necessitate limiting use of best practices to support needed flexibility for educational environments, students are aware of this as it is pervasive across education at this level to make this sort of accomodation. 

I would like to add more advanced cirriculum and it would be great to have content that goes through tillerless helm and a comprehensively secured helm example, and will definitely keep those in mind if nobody beats me to it. 

Thanks!

**Comment by scottslowe** [comment]
@afewellvmware Thanks for looking at this. I disagree with your assessment, but it's your choice to make. There are plenty of options to explore (namespace-specific Tiller instances with admin privileges in that namespace only, for example) before having to go "all the way" to a Tiller-less implementation. There is no better time than at the beginning to teach users to _properly_ secure their clusters.

(BTW, the presence of a tutorial on the Heptio web site should not be construed as a recommendation for a best practices installation.)

**Comment by afewell** [comment]
Thanks Scott, I really do want to get this right and dont want to miss an opportunity, but I dont think there is ever a scenario where every single possible best practice is always included in beginner level training, there is always a line somewhere, and so I am left to look at the principal, and the principal here is a universal one, to me the question comes down to should we ever use an admin account in a lab context rather than an account with the minimum possible permission which is always a best practice. I feel if we dont look at the question at this level, it would be an inconsistent policy, and I dont think its realistic to say that in all cases across windows/linux/vsphere/k8s etc in all training and lab guides we always have to use production grade rbac with least privilege. 

I think it is very analogous to saying we should never run a k8s manifest without a microsegmentation security policy, we have lots of labs that may not include a security policy and I dont think that implies in any way people shouldn't have a security policy, its just not the focus of every lab. 

Sorry I dont mean to soapbox I am really trying to think deeply about the issue and would really love for others to share their opinion as I am not trying to just say my feeling on this issue is necessarily right. In any case, the intent of the community is to have a crawl walk run approach from more basic/entry level use cases and advance towards full production grade implementations, and we are still much closer to the former than the latter. We absolutely plan to introduce cirriculum and implement actual production grade systems where and do fully intend to have additional training and enablement at that level. 

I will keep my ear to this for additional opinion, and also be open to reviewing any PRs on the issue, if there is a good way we can be a little more prescriptive with best practices while still keeping it a beginner level intro, I am happy to consider that. 

Thanks!

**Comment by afewellvmware** [comment]
Hey @scottslowe I was updating the helm lab for wwko this week and wasnt sure Id have time, but I was able to get the lab guide updated for tillerless helm. I left both options in there for students so they could see a basic rbac/admin config but I added a strong note to never use that in any real environment, and I also setup the lab to steer students toward the tillerless method unless they specifically want to do the example rbac/admin method. 

Thanks again for this input!
