### ISSUE TITLE
Getting error about basic_topology.yml while trying to deploy nsx-t pipeline

### ISSUE THREAD

**Issue by sthatte98** [CNA-Tech/PKS-Ninja#339]

**Comment by afewellvmware** [comment]
I have replicated and confirmed this bug, not sure what the root cause is yet, will update here once a resolution is available. 

In the meantime, please use the nsxt manual installation procedure, or load CNABU-PKS-Ninja-v11-nsxtInstalled template, which already has nsxt installed and allows you to skip past this step.

**Comment by afewellvmware** [comment]
Ok so I have a resolution to this now ... I did not get an explanation on root cause, but the source repo for the nsxt pipeline is updated, I will update the nsxt pipeline lab guide shortly. 

Workaround steps:

If you have a fresh template, before bringing up docker compose or loading any pipelines, enter the following commands:

```bash
cd ~/nsx-t-datacenter-ci-pipelines
git pull
```

Then you can proceed with the existing steps to bring up concourse, load and execute the pipelines. 

If you have already attempted to deploy the pipeline and it is currently in a failed state, issue the following commands to clean up your existing pipeline, update your repository and then redeploy the updated pipeline:

```bash
cd ~/nsx-t-datacenter-ci-pipelines
fly-d
git pull
cd ~/concourse
docker-compose down
```
The above commands both reset and update your failed pipeline deployment, after you enter the above you can proceed to load concourse and load and execute the pipelines.

**Comment by afewellvmware** [comment]
I just updated the nsxt pipeline install lab guide so this issue is now resolved.
