### ISSUE TITLE
image pull back off

### ISSUE THREAD

**Issue by leeadh** [CNA-Tech/PKS-Ninja#366]
Hi When I am trying to deploy the planespotter, I changed the yaml file for the kubernetes deployment to my local registry (public) with my planespotter container inside. 

I keep getting an image pullback off when I do the https://github.com/CNA-Tech/PKS-Ninja/tree/master/LabGuides/DeployPlanespotter-DP6539

what is wrong?

**Comment by natereid72-vmware** [comment]
Make sure you create the storage class for your cluster context


________________________________

**Comment by leeadh** [comment]
hi where do we set that? It didnt state in this guide to set the storage class?

**Comment by natereid72-vmware** [comment]
Yep, forgot that the lab was changed to use that later. So, if you've modified the mysql manifest per the lab, it shouldn't be an issue. You probably have a issue with your registry credentials or image path. Use 'kubectl  describe pod [pod name]' to get more info on the error.

**Comment by leeadh** [comment]
HI @natereid72-vmware  thank you will try out and will do end-end and see. 

I am getting the error when I deploy **just** the front end which Im not sure if this is correct.

**Comment by natereid72-vmware** [comment]
I'm unclear if you're using Harbor or some other registry. The front end image is the only one that is pulled from a private registry based on lab guides. So that further leads to an issue with either reference to image by name or authentication to registry. Check your docker login per the intro to Harbor lab.

**Comment by leeadh** [comment]
HI @natereid72-vmware  I am using harbor as my registry.  I am able to push the image successfully into the repo . I had already done docker login as I was able to push. Thank you once again

**Comment by leeadh** [comment]
![image](https://user-images.githubusercontent.com/15122358/56480775-307cf380-64ee-11e9-9ed2-753c5c69aa37.png)

```
  Type     Reason          Age                From                                           Message
  ----     ------          ----               ----                                           -------
  Normal   Scheduled       45s                default-scheduler                              Successfully assigned planespotter/planespotter-frontend-85df47d9d6-vv4qd to 1dce5e2c-6fa4-401c-9408-edb20bb22dc6
  Normal   Pulling         25s (x2 over 42s)  kubelet, 1dce5e2c-6fa4-401c-9408-edb20bb22dc6  pulling image "harbor.corp.local/planespotter/frontend:v1"
  Warning  Failed          25s (x2 over 42s)  kubelet, 1dce5e2c-6fa4-401c-9408-edb20bb22dc6  Failed to pull image "harbor.corp.local/planespotter/frontend:v1": rpc error: code = Unknown desc = Error response from daemon: Get https://harbor.corp.local/v2/: x509: certificate signed by unknown authority
  Warning  Failed          25s (x2 over 42s)  kubelet, 1dce5e2c-6fa4-401c-9408-edb20bb22dc6  Error: ErrImagePull
  Normal   BackOff         8s                 kubelet, 1dce5e2c-6fa4-401c-9408-edb20bb22dc6  Back-off pulling image "harbor.corp.local/planespotter/frontend:v1"
  Warning  Failed          8s                 kubelet, 1dce5e2c-6fa4-401c-9408-edb20bb22dc6  Error: ImagePullBackOff
```


I think I found the source and it says that it not able to pull the image because of the cert. However, I had already set the cert piror by coping the certificate in  opsmanager  and setting it in the cli console . Also, if I had not done this I wouldnt have been able to push earlier to harbor. As such, is there any any additional configuration we need to set up ?

**Comment by natereid72-vmware** [comment]
I don't know where the labs on this topic all come together at this point. That's showing a notary issue. You can enter this on your workstation 'export DOCKER_CONTENT_TRUST=0' and then upload the image to harbor again. Then it will work. There is a very specific way required to implement notary and pks generated clusters or notary to work correctly.

**Comment by leeadh** [comment]
Dear @natereid72-vmware  will try a while more and let u know if I come across any fix. my docker content trust was 0 already when I deployed initially.

**Comment by leeadh** [comment]
dear @natereid72-vmware tried this again. created a new project, set my content_trust to 0 and pushed. Push successfully into the repo and I ensured the image has content trust turned off.  it still gave me this error when I tried to do a kubectl create -f frontend-deployment_fromHarbor.yaml

**Comment by afewellvmware** [comment]
Hi @leeadh I would suspect your issue is likely that your kubernetes cluster deployment did not have the bosh trusted cert feature setup when you deployed the cluster ... this isnt related to content trust or login authentication, what happens is that for any container engine including the container engine running on the kubernetes worker nodes, they need to have a valid certificate for harbor to be able to pull from harbor. 

The best way to handle this is to enable the bosh trusted cert feature, which signs all bosh deployed services to be signed with the opsman cert, and once this option is selected everything that bosh deploys gets signed and you dont have to think about it again after you enable the feature. 

From within your pod, open a browser to opsman, login with admin/VMware1! and go to the bosh director for vsphere tile, go to the security tab, check the box for "Include OpsManager Root CA in Trusted Certs" and click save. Then go to the "Installation Dashboard > Review Pending Changes" screen and click Apply Changes. This will force a redeploy/update to the existing deployments and may take ~45 minutes in the low-performance lab environment, and after that everything should work fine. 

There is a new template called CNABU-PKS-Ninja-v11-ClusterReady1.1, I am not sure if that is available everywhere yet but this new template should have the bosh trusted cert feature pre-installed so once you can access this new template, you should not need to do this. Also, if you install PKS via concourse pipeline, our current pipeline configuration does not have this enabled so you would need to manually set it. The feature is supported in the pipeline we just havent modified our pipeline parameters to include it yet. 

Thanks!

**Comment by leeadh** [comment]
dear @afewell Thank you for this and I will certainly try it.  will keep you updated also. Thank you!

**Comment by natereid72** [comment]
leeadh, apologies for the run aroud, I had no power adapter for my laptop until yesterday and was working from my phone. I was able to log in to the template today and Art is correct. The bosh self-signed CA cert resolution should get your issue resolved. @afewell as a heads up, it doesn't look like the bosh-security-cert box is checked in the v11 cluster deployed template either. The lab guides no longer include (I can't locate at least) the directions to manually add root ca to Harbor tile. There is direction in the Harbor pipeline lab guide to check the bosh box, which should be equivalent, but the wording probably needs some editing. I'll make some updates later today.
