### ISSUE TITLE
Transfer Baseline-0.6 Template for FEL/VLP/QD Access

### ISSUE THREAD

**Issue by afewell** [CNA-Tech/PKS-Ninja#514]

**Comment by afewellvmware** [comment]
Opened ticket #INTSD-13571 with the Cloud Operations Service Desk to transfer the new template for FEL/VLP access

**Comment by afewellvmware** [comment]
Link to track COSD ticket status: https://servicedesk.eng.vmware.com/servicedesk/customer/portal/7/INTSD-13571

**Comment by afewellvmware** [comment]
Found problem with template, need to further adjust CPU allocation per issue #503. Cancelled ticket, initiating rebuild and will open new transfer ticket after rebuild.

**Comment by afewellvmware** [comment]
Completed and validated updated build, re-initiating transfer. Opened ticket INTSD-13592, status at: https://servicedesk.eng.vmware.com/servicedesk/customer/portal/7/INTSD-13592

**Comment by pks-ninja-labs-owners** [comment]
Still no results from help desk, their ticket reported it as completed though there is no evidence it was ever completed, still not available. Added another request for escalation to cosd and initiated manual transfer as an attempt to reconcile since help desk requests are ineffective. 

![image](https://user-images.githubusercontent.com/55507284/65999904-34288500-e453-11e9-9170-5fedac439cdd.png)

**Comment by pks-ninja-labs-owners** [comment]
![image](https://user-images.githubusercontent.com/55507284/66000360-1a3b7200-e454-11e9-9602-36f44c734b20.png)
