### ISSUE TITLE
DeployFirstCluster-DC1610 - uaac target issue

### ISSUE THREAD

**Issue by fitz0017** [CNA-Tech/PKS-Ninja#562]
Can not target uaa after ssh'ing into ubuntu@opsman.corp.local
when using uaac from cli-vm everything seems to work fine.

if other's don't see an issue with it, I would recommend just removing the step suggesting to ssh into opsman

cluster creation after using uaac from cli-vm worked fine

**Comment by afewellvmware** [comment]
Hey @fitz0017 that is funny I just ran into this same issue to, and the exact same resolution. The problem is that opsman vm has one ethernet directly on the pks management subnet, so it needs to communicate with the private IP of opsman but I think the cert uses the hostname and the external dns resolves to the external IP which opsman cant use. I haven't gone back to dissect if this was really how it was configured in the past or if there was some difference that made it work, but in any case I think the best fix is to use it from CLI-VM. In v12 we have bosh and more other tools on cli-vm now specifically because we wanted to use it more for stuff like this. I should have already patched this but you beat me to making an issue ticket so you get the points :)
