### ISSUE TITLE
pks-mgmt-2 resource pool does not exist

### ISSUE THREAD

**Issue by sudhakarau1** [CNA-Tech/PKS-Ninja#59]
https://github.com/CNA-Tech/PKS-Ninja/tree/master/LabGuides/PksInstallPhase1-IN3138 
For Step 2.5 Create Availability Zones, the 3rd AZ resource pool doesn't exist. The opsman error is:
" Please review the errors below
Cannot find availability zone 'RegionA01-COMP01:pks-mgmt-2', type: AvailabilityZonesVerifier
All errors will be reverified before installation."

**Comment by natereid72** [comment]
This seems like a versioning issue. I went through this lab guide two weeks back and this wasn't in the directions.

**Comment by afewell** [comment]
Hey Freddy sorry for the delay, that is because in the v7 version of the template there was a mgmt-2, but in the v10 template there is not, there is only a single pks mgmt net. The use of the mgmt-2 network in the previous template was a temporary workaround for something different, we actually had management hosts on the compute cluster, and in v10 the design is cleaner. 

This is one of the consistent things you should run into a lot in the current lab guides, most were mode using a v7 template and the goal is to get them all in line with the v10, thanks!
