### ISSUE TITLE
Lab 4 Harbor, Planespotter image push

### ISSUE THREAD

**Issue by ragsgit** [CNA-Tech/PKS-Ninja#64]
Image push fails from cli-vm. Possibly another DNS resolution issue?

```
root@cli-vm:~/planespotter/frontend# docker push harbor.corp.local/library/frontend:v1
The push refers to repository [harbor.corp.local/library/frontend]
Get https://harbor.corp.local/v2/: dial tcp: lookup harbor.corp.local: no such host
root@cli-vm:~/planespotter/frontend
```

**Comment by ragsgit** [comment]
Here is how I solved it:

cli-vm may not DNS resolve harbor.corp.local
Find the IP address (10.40.14.5) of the harbor host from the ControlCenter (RDP desktop) DNS Mgr and add the IP address to /etc/hosts of cli-vm. After that do a docker login and then push!

**Comment by natereid72-vmware** [comment]
For it being 10.40.14.6, I believe this is an issue due to the way bosh deploys Harbor. We should probably add directions to the lab guide to _"Update the DNS entry for the Harbor hostname with the IP address of the Harbor VM assigned by BOSH. Get the IP assigned to Harbor by clicking the Harbor Tile and selecting the Status tab."_ as per https://docs.pivotal.io/partners/vmware-harbor/installing.html#configure_az_networks 

My guess is that the per-configured DNS record is optimistic based on order of deploying components. If something deploys out of order, then BOSH assigns IPs that don't match existing DNS records.

 For it being 10.40.14.5, that's what it should be per the per-configured DNS record and NSX-T NAT rule. That would be an issue of the cli-vm dns client. This is fixed with posted resolution for cli-vm dns issues.

**Comment by afewellvmware** [comment]
Instructions have all been updated to use Nate's script which patches this issue, closing
