### ISSUE TITLE
One ESXI host always fails to connect when i use NASA or SDDC cloud with  NSXT Password expired on v12-ClusterReady-0.5 template

### ISSUE THREAD

**Issue by leoncozzi** [CNA-Tech/PKS-Ninja#686]
Everytime i load the v12-ClusterReady-0.5 template on Sandox-SDDC or NASA, one of the ESXI hosts is uncontactable. It is not consistant. Sometimes ESXi04 sometimes ESXi02. I can ping all the others hosts, but not the one i cannot contact. It shows as disconnected on Vcenter. When i log into the console it shows the static IP is assigned. All connectivity on the vcloud director interfaces looks. good. The template is therefore not useable on the onecloud environments i have access to. Does anyone know why this is happening and could offer a fix?

**Comment by pks-ninja-labs-rw** [comment]
Hi Leon, thanks for documenting your issue here. Per our seperate discussion, unfortunately different onecloud orgs have different levels of performance and some are running older hardware or oversubscribed. I added you to access VLP with access to run a pod for 7 days at a time, hopefully that will work for you. It is also possible the onecloud team may be able to help with the issues you are having in your onecloud, you can open a ticket with the onecloud team by searching for "cloud operations service desk" in workspace one. 

Hopefully the VLP account will help meet your need, let me know if that works, thanks!
